Draft: feat(mysql): Support to configure db host
stuvusIT/wordpress pull request #35
Opened 2021-10-04 07:41 UTC by haslersn

2021-10-04 09:48 UTC, neumantm requested changes
Please update the readme

2021-10-04 09:48 UTC, neumantm commented on tasks/setup_wp_instance.yml
> +    wordpress_mysql_create_db: "{{ wp_instance.mysql_create_db | default(true) }}"
Where are these used?

2021-10-04 11:58 UTC, haslersn commented on tasks/setup_wp_instance.yml
> +    wordpress_mysql_create_db: "{{ wp_instance.mysql_create_db | default(true) }}"
https://github.com/stuvusIT/wordpress/pull/35/files#diff-90ddd283ab9a43ce2ca2a13325cb443e959a4ff27379c95cad99e58cf53725a2L2-L13

2021-11-13 15:25 UTC, neumantm approved these changes

2021-11-13 15:39 UTC, merged